### ISSUE TITLE
java.lang.NoClassDefFoundError: com/android/tools/r8/BackportedMethodListCommand

### ISSUE THREAD

**Issue by nikeorever** [JakeWharton/wormhole#10]
R8Version:1.6.67 (build 63035baeff4ab2f5079d99c54d86d9a4839c158c from go/r8bot (luci-r8-ci-xenial-7-83cg))
Android Studio:3.6
Gradle:5.6.4
OS:Linux

**Comment by JakeWharton** [comment]
AGP 4.0.0 or newer is required. I can add an AGP version check to the plugin.

**Comment by nikeorever** [comment]
> AGP 4.0.0 or newer is required. I can add an AGP version check to the plugin.

ok
