### ISSUE TITLE
java.util.function support for Android < 24

### ISSUE THREAD

**Issue by 2beaucoup** [JakeWharton/wormhole#13]
It looks like `java.util.function.*` isn't supported on Android Marshmallow and below. Would it be possible to provide it via wormhole?

I'm currently seeing exception like
> `java.lang.NoClassDefFoundError: some.package.-$$Lambda$MyClass$eHkBeSAX-ELQ36nABmRY-PheZyM`

at runtime.

There are projects like [android-retrostreams](https://github.com/retrostreams/android-retrostreams) that [re-implement](https://github.com/retrostreams/android-retrostreams/tree/master/src/main/java/java9/util/function) these interfaces but that doesn't help if a third party is depending on it.

**Comment by JakeWharton** [comment]
Functional interfaces are backported as of AGP 4.0. See https://developer.android.com/studio/preview/features#j8-desugar. I don't know how far down they go. Probably to API 14. #2 tracks being able to correctly query and update the lint warnings for desugared types. Currently only desugared methods are known by the tool.

Wormhole isn't providing any functionality for desugaring. It's just making the existing support inside D8/R8/AGP easier to use. Any feature requests for new things should go towards AGP or D8.
