### ISSUE TITLE
Advantages of this tool over desugar support in AGP 4.0

### ISSUE THREAD

**Issue by simonsickle** [JakeWharton/wormhole#16]
https://developer.android.com/studio/write/java8-support#library-desugaring

Android studio can now desugar libraries like java.time with `coreLibraryDesugaring`. Are there benefits to using wormhole over this official method (ie are there classes not picked up by the `desugar_jdk_libs` library) or should I migrate over?

Thanks

**Comment by JakeWharton** [comment]
Library desugaring backports existing APIs in the framework to work on older versions of Android before they otherwise would be available. This tool exposes APIs that don't exist yet in the framework but are supported to be backported. The two things don't compete, they compliment each other!

**Comment by JakeWharton** [comment]
The example in the readme is for `List.copyOf`, for example. This is not available normally in the framework but wormhole makes it available. Compare that to `List.of` which is available in API 30 but able to be backported by D8.
