### ISSUE TITLE
Use AGP API for getting SDK dir

### ISSUE THREAD

**Issue by nikeorever** [JakeWharton/wormhole#9]
When i add compileSdkVersion use `AndroidWormhole.create(29)`, An exception was thrown by gradle:
A problem occurred evaluating project ':app'.
> java.lang.NullPointerException (no error message)

**Comment by JakeWharton** [comment]
Can you run with `--stacktrace`?

**Comment by nikeorever** [comment]
> Can you run with `--stacktrace`?
Sorry，ANDROID_HOME does not exist in my enviroment variable,

**Comment by nikeorever** [comment]
54  val sdkDir = Paths.get(System.getenv("ANDROID_HOME")) // TODO Find AGP canonical internal API.

> Can you run with `--stacktrace`?

54  val sdkDir = Paths.get(System.getenv("ANDROID_HOME")) // TODO Find AGP canonical internal API.

**Comment by JakeWharton** [comment]
Ah, yes. Thanks. This was a quick-and-dirty way to get off the ground but I need to switch to querying wherever AGP thinks the SDK is.
